---
title: "Homework 2 Article Critique"
author: "Taylor Thul"
date: "Feb 8, 2017"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

## **Homework 2**

Becoming a nurse in the “digital age” necessitates at least baseline understanding and fluency in utilizing electronic health records (EHR).  It is surprising, given the seeming ubiquity of EHRs, that Congress passed the Health Information Technology for Economic and Clinical Health Act less than a decade ago.  In the context of such a rapid change in data capture and storage in such a short amount of time, there was bound to be growing pains for clinicians and researchers alike.  The author’s purpose in this article seemed to be to discuss some of these growing pains, both challenges and opportunities to give a high level accounting of using EHR data in nursing research.  This topic is hugely important for health related researchers of all disciplines.  Never before has so much data been captured, stored, and had the potential for use in analysis.  As the fictional Ben Parkers says “with great power comes great responsibility” and with big data comes big responsibility.  Utilizing EHR data has the potential to improve impatient care and health outcomes, but must be treated appropriately and with respect.  
The article first presents the challenges in EHR data as related to implementation, data presentation, and security concerns.  Specifically they posit researchers may encounter problems related to defining variables within and across health systems and proprietary EHR systems as well as the possibly of poor data entry from the very structure of the EHR.   For example forced choices within documentation may limit the understanding of the true clinical picture whereas free text sections may produce textual data difficult to analysis.  Furthermore, researchers will likely encounter challenges in data security in the face of such large and possibly uncoordinated systems.  Contrasting this the authors present the opportunities related to EHR including Big Data and data mining.  If improvements in patient care is the ultimate goal of utilizing EHR data, though not directly states in the article, big data analysis through methods like data minding 
The paper seems to be aiming to give a broad overview of the challenges and opportunities of EHR data so each point does not have mountains of supporting evidence.  However, the overall points do seem well supported and the evidence flows logically into their conclusions.  The citations seem to mostly be from reputable journals or governmental documents, supporting the credibility of evidence presented.  Though the article did seem to fulfill its purpose, I believe their attention could’ve been more evenly divided between challenges and opportunities.  The opportunities presented seem shallow compared to the challenges.  There are so many opportunities for using EHR data and it felt the authors did not give a complete picture.  
The main implications of their findings involve awareness of the complexities working with EHR data before jumping into a project.  The authors specifically discuss understanding privacy requirements, awareness of how data has been entered into the EHR, joining the organizational informational technologist for report generation, and advocating for standardization of electronic documentations.   The only further implication I came away from this paper with is the importance of communication when utilizing EHRs for research.  The nursing researcher needs excellent communication with a variety of hospital departments including information technology, informatics, and the clinicians themselves to understand how data is being entered and stored.  It seems knowing how the EHR is created and utilized will help in variable definition and data analysis.  Overall I thought this was a good paper and I feel I have a better high level view of the complexities of using EHR data.  

